### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by JustRadical** [JustTemmie/beaverDNS#1]
Please tell me what this repo is please

**Comment by JustTemmie** [comment]
beaver

**Comment by JustRadical** [comment]
but what does it do?

**Comment by JustTemmie** [comment]
beaver things

**Comment by JustRadical** [comment]
seriously whatttt

**Comment by JustTemmie** [comment]
wifi

**Comment by JustRadical** [comment]
im confused

**Comment by JustRadical** [comment]
why is it python?

**Comment by JustTemmie** [comment]
why is it not python?

**Comment by JustRadical** [comment]
I don't get it

**Comment by JustTemmie** [comment]
nono answer me

**Comment by JustTemmie** [comment]
what else would it be?

**Comment by JustRadical** [comment]
My point was I dont know what this is even doing, and if it has something to do with DNS then why is it python and not a more low level language

**Comment by JustTemmie** [comment]
because python epic sunglasses emoji
